const NORMALIZATION_METHODS = {
  MIN_MAX: 'min-max',
  Z_SCORE: 'z-score',
  LOG: 'log',
  BOX_COX: 'box-cox',
};

export const NORMALIZATION_METHOD_TYEPES = [
  NORMALIZATION_METHODS.BOX_COX,
  NORMALIZATION_METHODS.Z_SCORE,
  NORMALIZATION_METHODS.LOG,
  NORMALIZATION_METHODS.MIN_MAX,
];
